version: "3.9"
services:
  oracle-db-enterprise:
    image: oracle_enterprise:19.3.0
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      # The data volume to use for the database. Has to be writable by the Unix "oracle" (uid: 54321) user inside the container!
      - /opt/oracle/oradata:/home/ericambiel/Desktop/docker_volumes/$npm_package_name/oradata
      # Optional: A volume with custom scripts to be run after database startup.
#      - /opt/oracle/scripts/startup:/home/ericambiel/Desktop/docker_volumes/$name/startup
      # Optional: A volume with custom scripts to be run after database setup.
#      - /opt/oracle/scripts/setup:/home/ericambiel/Desktop/docker_volumes/$name/setup
    environment:
      # The Oracle Database SID that should be used (default: ORCLCDB).
      - ORACLE_SID=ORCL
      # The Oracle Database PDB name that should be used (default: ORCLPDB1).
      - ORACLE_PDB=ORCLPDB1
      # The Oracle Database SYS, SYSTEM and PDB_ADMIN password (default: auto generated).
      - ORACLE_PWD=1234567890Abc
      # The total memory in MB that should be used for all SGA components (optional).
      #                  Supported 19.3 onwards.
#      - INIT_SGA_SIZE=<your database SGA memory in MB>
      # The target aggregate PGA memory in MB that should be used for all server processes attached to the instance (optional).
      #                  Supported 19.3 onwards.
#      - INIT_PGA_SIZE=<your database PGA memory in MB>
      # To enable auto calculation of the DBCA total memory limit during the database creation, based on
      # the available memory of the container, which can be constrained using the `docker run --memory`
      # option. If set to 'false', the total memory will be set as 2GB (default: true).
      # Note that this parameter is not taken into account if the `-e INIT_SGA_SIZE` or `-e INIT_PGA_SIZE`
      # are set.
      #                  Supported 19.3 onwards.
      - AUTO_MEM_CALCULATION=true
      # The Oracle Database Edition (enterprise/standard).
      #                  Supported 19.3 onwards.
      - ORACLE_EDITION=enterprise
      # The character set to use when creating the database (default: AL32UTF8).
      - ORACLE_CHARACTERSET=AL32UTF8
      # To enable archive log mode when creating the database (default: false).
      #                  Supported 19.3 onwards.
      - ENABLE_ARCHIVELOG=true
