version: "3.9"
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: "dozzle"
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Number of lines that will be required in the console.
      - DOZZLE_TAILSIZE=5000
      - DOZZLE_LEVEL=info
